import { createStyles } from "@mantine/core";

export const useStyles = createStyles((theme) => ({
    container: {
        position: "relative",
        width: "100%",
        minHeight: "100vh",
        backgroundColor: "#f5f5f5",
        overflow: "hidden",
        ":before": {
            content: "",
            position: "absolute",
            width: "2000px",
            height: "2000px",
            borderRadius: "50%",
            background: "linear-gradient(-45deg, #4481eb, #04befe)",
            top: "-10%",
            right: "48%",
            transform: "translateY(-50%)",
            zIndex: 6,
            transition: "1.8s ease-in-out",
        },
        formsContainer: {
            position: "absolute",
            width: "100%",
            height: "100%",
            top: "0",
            left: "0",
            signinSignup: {
                position: "absolute",
                top: "50%",
                left: "75%",
                transform: "translate(-50%, -50%)",
                width: "50%",
                display: "grid",
                gridTemplateColumns: "1fr",
                zIndex: 5,
                transition: "1s 0.7s ease-in-out",
                signInForm: {
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    flexDirection: "column",
                    padding: " 0 5rem",
                    overflow: "hidden",
                    gridColumn: "1 / 2",
                    gridRow: " 1 / 2",
                    transition: "0.2s 0.7s ease-in-out",
                    zIndex: 2,
                },
            },
        },
    },
}));
